# Part 2. Vector and Matrix

In this lab, we will learn how to use Python to operate vectors and matrices. 

## 1. Example

### 1.1 Load data with pandas

In [3]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


### 1.2 Operation for vector

In [29]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


### 1.3 Operation for matrix

In [32]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


## 2 Task

### 2.1 Get the first column and the second to last column from X

In [30]:
# this is your code to get two vectors
c1 = X[:, 0]
c2 = X[:, -1]
print(c1[0:10])
print(c2[0:10])

[18.0 15.0 18.0 16.0 17.0 15.0 14.0 14.0 14.0 15.0]
[70 70 70 70 70 70 70 70 70 70]


### 2.2 Perform following operations on these two vectors and print the result

In [33]:

# 1. addition and subtraction
add = c1 + c2
subtr = c1 - c2
print(f"Addition: {add[0:10]}")
print(f"Subtraction: {subtr[0:10]}")
# 2. element-wise multiplication
multi = np.multiply(c1, c2)
print(f"Element multiplication: {multi[0:10]}")
# 3. inner product
inner = np.inner(c1,c2)
print(f"Inner product: {inner}")
# 4. three norms
l1 = np.linalg.norm(c1, ord=1)
l2 = np.linalg.norm(c1, ord=2)
max_norm = np.linalg.norm(c1 ,ord=np.inf)
print(f"l1: {l1}")
print(f"l2: {l2}")
print(f"max_norm: {max_norm}")
# 5. compute the distance between these two vectors
dista = np.linalg.norm(c2-c1, ord=1)
print(f"Distance: {dista}")

Addition: [88.0 85.0 88.0 86.0 87.0 85.0 84.0 84.0 84.0 85.0]
Subtraction: [-52.0 -55.0 -52.0 -54.0 -53.0 -55.0 -56.0 -56.0 -56.0 -55.0]
Element multiplication: [1260.0 1050.0 1260.0 1120.0 1190.0 1050.0 980.0 980.0 980.0 1050.0]
Inner product: 718009.0999999995
l1: 9358.800000000003
l2: 494.28813459357895
max_norm: 46.6
Distance: 21465.199999999993


### 2.3 Get the first three columns and the last three columns from X

In [37]:
# this is your code to get two matrices: A, B
d1 = X[:, 0:3]
d2 = X[:, -3:]
print(d1[0:10])
print()
print(d2[0:10])

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 [16.0 8 304.0]
 [17.0 8 302.0]
 [15.0 8 429.0]
 [14.0 8 454.0]
 [14.0 8 440.0]
 [14.0 8 455.0]
 [15.0 8 390.0]]

[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 [3433 12.0 70]
 [3449 10.5 70]
 [4341 10.0 70]
 [4354 9.0 70]
 [4312 8.5 70]
 [4425 10.0 70]
 [3850 8.5 70]]


### 2.4 Perform following operations on these two matrices and print the result

In [51]:
# 1. addition and subtraction
add2 = d1 + d2
sub2 = d1 - d2
print(add2[0:5])
print()
print(sub2[0:5])

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
C = np.transpose(d2)
print(f"C shape: {C.shape}")
# 3. compute the product between A and C, and print the result and its shape
prod = np.matmul(d1, C)
print(f"Product result: {prod}")
print(f"Product shape: {prod.shape}")
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
D = np.transpose(d1)
print(f"D shape: {D.shape}")
# 5. compute the product between D and B, and print the result and its shape
prod2 = np.matmul(D, d2)
print(f"Product result: {prod2}")
print(f"Product shape: {prod2.shape}")

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 [3449.0 20.0 374.0]
 [3466.0 18.5 372.0]]

[[-3486.0 -4.0 237.0]
 [-3678.0 -3.5 280.0]
 [-3418.0 -3.0 248.0]
 [-3417.0 -4.0 234.0]
 [-3432.0 -2.5 232.0]]
C shape: (3, 406)
Product result: [[84658.0 88056.0 83426.0 ... 66576.8 72572.8 74289.2]
 [77156.0 79987.0 76128.0 ... 63217.8 68223.8 69655.2]
 [85428.0 88826.0 84196.0 ... 67478.8 73474.8 75191.2]
 ...
 [121626.0 127672.0 119446.0 ... 84556.4 95144.4 98187.6]
 [106560.0 111850.0 104652.0 ... 74146.4 83414.4 86077.6]
 [117002.0 122859.0 114890.0 ... 80949.4 91207.4 94155.6]]
Product shape: (406, 406)
D shape: (3, 406)
Product result: [[25614040.900000002 149295.04000000004 718009.0999999995]
 [7149030 33484.69999999997 167835]
 [269175402.0 1160836.2999999998 5943079.0]]
Product shape: (3, 3)
